### PR TITLE
Fix various issues

### PR DESCRIPTION
**Pull request by clagms**

### CODE REVIEW

**Review by masoud-najafi — COMMENTED** [review]
Hi, I cannot find the binaries. Please share the binaries to check them all.

**Comment by clagms** [comment]
> Hi, I cannot find the binaries. Please share the binaries to check them all.

You can find them here @masoud-najafi : https://github.com/clagms/synchronous-clock-fmus/actions/runs/12082597376/artifacts/2253146983

Apologies for the delay.

**Comment by masoud-najafi** [comment]
> > Hi, I cannot find the binaries. Please share the binaries to check them all.
> 
> You can find them here @masoud-najafi : https://github.com/clagms/synchronous-clock-fmus/actions/runs/12082597376/artifacts/2253146983
> 
> Apologies for the delay.

Hi Claudio,
FMUs in the zip file do not contain the XML. Please check it again.
Thanks
Masoud

**Comment by clagms** [comment]
Silly me. Here they are @masoud-najafi : https://filesender.deic.dk/?s=download&token=dde239ae-8340-4b9b-b67a-b34eef429d13

**Comment by masoud-najafi** [comment]
The entire model works fine with the new binaries.

**Review by masoud-najafi — APPROVED** [review]

**Comment by clagms** [comment]
Thanks for your feedback! @YonVanom has identified an important [issue](https://github.com/clagms/synchronous-clock-fmus/issues/10) to be addressed here.

**Comment by clagms** [comment]
Now https://github.com/clagms/synchronous-clock-fmus/issues/10 is fixed. @masoud-najafi , can you kindly test the new binaries when you have some time. Note that the controller x input is gone, as it was not being used, so you need to adjust the co-simulation scenario. Other than that, I don't expect problems. The new binaries are here for download: https://filesender.deic.dk/?s=download&token=992fd639-7396-4b19-9221-1bd47a4c5af7 

Thanks @YonVanom for also pointing out the delay in the time event detection for the cosim. Now the delays between CS and ME are the same, but it's still taking a one step delay to detect the event. For now, I'm leaving it as it is, to avoid changing the ME orchestration.

**Review by masoud-najafi — APPROVED** [review]
Git the same result as before.

**Review by YonVanom — APPROVED** [review]
Successfully built from source using the instructions provided. Ran fine using the example CS and ME importers.

There's still a small difference between CS and ME on my end:
- CS: controller output first updates at 0.1**1**s and then every 0.11s
- ME: controller output first updates at 0.1**0**s and then every 0.11s

So there is a small initial delay between the two, but they update at the same interval after that.
Output traces (plant behavior) are the same for both CS and ME when accounting for the delay (shifting by 1 sample).

**Pull request merged**
